
class CountryCodes {


  static validatePhoneNumber (_number) {
    return true;

    // if( !number || number === "" ){
    //   return false;
    // }

    //  return /^(1\s|1|)?((\(\d{3}\))|\d{3})(\-|\s)?(\d{3})(\-|\s)?(\d{4})$/.test(number.toString());
     
  }



  //try our best to format the number like: +1 (111) 222-3333
  static formatPhoneNumber (code, number) {

    const phone_number = ('' + number).replace(/\D/g, '');
    const match = phone_number.match(/^(\d{3})(\d{3})(\d{4})$/);
    
    if (match) { 
         const formatted_phone_number = '(' + match[1] + ') ' + match[2] + '-' + match[3];
         return `${code}${formatted_phone_number}`;
    };

    //if all else fails return the country code + phone number
    return `${code}${phone_number}`;
  }


  static getCodes(){
    return [{"key":"us","name":"United States","code":"+1", "icon": "&#x1F1FA&#x1F1F8"},
            {"key":"ca","name":"Canada","code":"+1", "icon": "&#x1F1E8&#x1F1E6"},
            {"key":"gb","name":"United Kingdom","code":"+44", "icon": "&#x1F1EC&#x1F1E7"},
            {"key":"mx","name":"Mexico (México)","code":"+52", "icon": "&#x1F1F2&#x1F1FD"},
            {"key":"dz","name":"Algeria (‫الجزائر‬‎)","code":"+213", "icon":"&#x1F1E9&#x1F1FF"},
            {"key":"as","name":"Samoa","code":"+1684", "icon": "&#x1F1FC&#x1F1F8"},
            {"key":"ad","name":"Andorra","code":"+376", "icon": "&#x1F1E6&#x1F1E9"},
            {"key":"ao","name":"Angola","code":"+244", "icon": "&#x1F1E6&#x1F1F4"},
            {"key":"ai","name":"Anguilla","code":"+1264", "icon": "&#x1F1E6&#x1F1EE"},
            {"key":"ag","name":"Antigua and Barbuda","code":"+1268", "icon": "&#x1F1E6&#x1F1EC"},
            {"key":"ar","name":"Argentina","code":"+54", "icon": "&#x1F1E6&#x1F1F7"},
            {"key":"am","name":"Armenia (Հայաստան)","code":"+374", "icon": "&#x1F1E6&#x1F1F2"},
            {"key":"aw","name":"Aruba","code":"+297", "icon": "&#x1F1E6&#x1F1FC"},
            {"key":"ac","name":"Ascension Island","code":"+247", "icon": "&#x1F1E6&#x1F1FC"},
            {"key":"ax","name":"Finland Åland Islands","code":"+358", "icon": "&#x1F1EB&#x1F1EE"},
            {"key":"au","name":"Australia","code":"+61", "icon": "&#x1F1E6&#x1F1FA"},
            {"key":"at","name":"Austria (Österreich)","code":"+43", "icon": "&#x1F1E6&#x1F1F9"},
            {"key":"az","name":"Azerbaijan (Azərbaycan)","code":"+994", "icon": "&#x1F1E6&#x1F1FF"},
            {"key":"bs","name":"Bahamas","code":"+1242", "icon": "&#x1F1E7&#x1F1F8"},
            {"key":"al","name":"Albania (Shqipëri)","code":"+355", "icon": "&#x1F1E6&#x1F1FD"},
            {"key":"af","name":"Afghanistan (‫افغانستان‬‎)","code":"+93", "icon": "&#x1F1E6&#x1F1EB"},
            {"key":"bh","name":"Bahrain (‫البحرين‬‎)","code":"+973", "icon": "&#x1F1E7&#x1F1ED"},
            {"key":"bd","name":"Bangladesh (বাংলাদেশ)","code":"+880", "icon": "&#x1F1E7&#x1F1E9"},
            {"key":"by","name":"Belarus (Беларусь)","code":"+375", "icon": "&#x1F1E7&#x1F1FE"},
            {"key":"be","name":"Belgium (België)","code":"+32", "icon": "&#x1F1E7&#x1F1EA"},
            {"key":"bz","name":"Belize","code":"+501", "icon": "&#x1F1E7&#x1F1FF"},
            {"key":"bb","name":"Barbados","code":"+1246", "icon": "&#x1F1E7&#x1F1E7"},
            {"key":"bj","name":"Benin (Bénin)","code":"+229", "icon": "&#x1F1E7&#x1F1EF"},
            {"key":"bm","name":"Bermuda","code":"+1441", "icon": "&#x1F1E7&#x1F1F2"},
            {"key":"bt","name":"Bhutan (འབྲུག)","code":"+975", "icon": "&#x1F1E7&#x1F1F9"},
            {"key":"br","name":"Brazil (Brasil)","code":"+55", "icon": "&#x1F1E7&#x1F1F7"},
            {"key":"io","name":"British Indian Ocean Territory","code":"+246", "icon": "&#x1F1EE&#x1F1F4"},
            {"key":"vg","name":"British Virgin Islands","code":"+1284", "icon": "&#x1F1FB&#x1F1EC"},
            {"key":"bw","name":"Botswana","code":"+267", "icon": "&#x1F1E7&#x1F1FC"},
            {"key":"bg","name":"Bulgaria (България)","code":"+359", "icon": "&#x1F1E7&#x1F1EC"},
            {"key":"bf","name":"Burkina Faso","code":"+226", "icon": "&#x1F1E7&#x1F1EB"},
            {"key":"bi","name":"Burundi (Uburundi)","code":"+257", "icon": "&#x1F1E7&#x1F1EE"},
            {"key":"kh","name":"Cambodia (កម្ពុជា)","code":"+855", "icon": "&#x1F1F0&#x1F1ED"},
            {"key":"cm","name":"Cameroon (Cameroun)","code":"+237", "icon": "&#x1F1E8&#x1F1F2"},
            {"key":"cv","name":"Cape Verde (Kabu Verdi)","code":"+238", "icon": "&#x1F1E8&#x1F1FB"},
            {"key":"bq","name":"Caribbean Netherlands Bonaire, Saba and Sint Eustatius","code":"+599", "icon": "&#x1F1E7&#x1F1F6"},
            {"key":"ky","name":"Cayman Islands","code":"+1345", "icon": "&#x1F1F0&#x1F1FE"},
            {"key":"cf","name":"Central African Republic (République centrafricaine)","code":"+236", "icon": "&#x1F1E8&#x1F1EB"},
            {"key":"td","name":"Chad (Tchad)","code":"+235", "icon": "&#x1F1F9&#x1F1E9"},
            {"key":"cn","name":"China (中国)","code":"+86", "icon": "&#x1F1E8&#x1F1F3"},
            {"key":"cl","name":"Chile","code":"+56", "icon": "&#x1F1E8&#x1F1F1"},
            {"key":"cx","name":"Christmas Island","code":"+61", "icon": "&#x1F1E6&#x1F1FA"},
            {"key":"cc","name":"Cocos (Keeling) Islands","code":"+61"},
            {"key":"co","name":"Colombia","code":"+57"},
            {"key":"km","name":"Comoros (‫جزر القمر‬‎)","code":"+269"},
            {"key":"cd","name":"Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)","code":"+243"},
            {"key":"cg","name":"Congo (Republic) (Congo-Brazzaville)","code":"+242"},
            {"key":"ck","name":"Cook Islands","code":"+682"},
            {"key":"cr","name":"Costa Rica","code":"+506"},
            {"key":"ci","name":"Côte d\'Ivoire","code":"+225"},
            {"key":"hr","name":"Croatia (Hrvatska)","code":"+385"},
            {"key":"cu","name":"Cuba","code":"+53"},
            {"key":"cw","name":"Curaçao","code":"+599"},
            {"key":"cy","name":"Cyprus (Κύπρος)","code":"+357"},
            {"key":"cz","name":"Czech Republic (Česká republika)","code":"+420"},
            {"key":"dk","name":"Denmark (Danmark)","code":"+45"},
            {"key":"dj","name":"Djibouti","code":"+253"},
            {"key":"ba","name":"Bosnia and Herzegovina (Босна и Херцеговина)","code":"+387"},
            {"key":"do","name":"Dominican Republic (República Dominicana)","code":"+1"},
            {"key":"ec","name":"Ecuador","code":"+593"},
            {"key":"eg","name":"Egypt (‫مصر‬‎)","code":"+20"},
            {"key":"sv","name":"El Salvador","code":"+503"},
            {"key":"gq","name":"Equatorial Guinea (Guinea Ecuatorial)","code":"+240"},
            {"key":"dm","name":"Dominica","code":"+1767"},
            {"key":"et","name":"Ethiopia","code":"+251"},
            {"key":"ee","name":"Estonia (Eesti)","code":"+372"},
            {"key":"fk","name":"Falkland Islands (Islas Malvinas)","code":"+500"},
            {"key":"bn","name":"Brunei","code":"+673"},
            {"key":"fj","name":"Fiji","code":"+679"},
            {"key":"fr","name":"France","code":"+33"},
            {"key":"fi","name":"Finland (Suomi)","code":"+358"},
            {"key":"pf","name":"French Polynesia (Polynésie française)","code":"+689"},
            {"key":"gf","name":"French Guiana (Guyane française)","code":"+594"},
            {"key":"gm","name":"Gambia","code":"+220"},
            {"key":"ga","name":"Gabon","code":"+241"},
            {"key":"ge","name":"Georgia (საქართველო)","code":"+995"},
            {"key":"de","name":"Germany (Deutschland)","code":"+49"},
            {"key":"fo","name":"Faroe Islands (Føroyar)","code":"+298"},
            {"key":"gi","name":"Gibraltar","code":"+350"},
            {"key":"gl","name":"Greenland (Kalaallit Nunaat)","code":"+299"},
            {"key":"gr","name":"Greece (Ελλάδα)","code":"+30"},
            {"key":"gd","name":"Grenada","code":"+1473"},
            {"key":"gp","name":"Guadeloupe","code":"+590"},
            {"key":"gt","name":"Guatemala","code":"+502"},
            {"key":"gg","name":"Guernsey","code":"+44"},
            {"key":"bo","name":"Bolivia","code":"+591"},
            {"key":"gy","name":"Guyana","code":"+592"},
            {"key":"ht","name":"Haiti","code":"+509"},
            {"key":"gn","name":"Guinea (Guinée)","code":"+224"},
            {"key":"gw","name":"Guinea-Bissau (Guiné Bissau)","code":"+245"},
            {"key":"hn","name":"Honduras","code":"+504"},
            {"key":"hk","name":"Hong Kong (香港)","code":"+852"},
            {"key":"hu","name":"Hungary (Magyarország)","code":"+36"},
            {"key":"is","name":"Iceland (Ísland)","code":"+354"},
            {"key":"id","name":"Indonesia","code":"+62"},
            {"key":"in","name":"India (भारत)","code":"+91"},
            {"key":"ir","name":"Iran (‫ایران‬‎)","code":"+98"},
            {"key":"im","name":"Isle of Man","code":"+44"},
            {"key":"gu","name":"Guam","code":"+1671"},
            {"key":"iq","name":"Iraq (‫العراق‬‎)","code":"+964"},
            {"key":"il","name":"Israel (‫ישראל‬‎)","code":"+972"},
            {"key":"jp","name":"Japan (日本)","code":"+81"},
            {"key":"jm","name":"Jamaica","code":"+1876"},
            {"key":"it","name":"Italy (Italia)","code":"+39"},
            {"key":"er","name":"Eritrea","code":"+291"},
            {"key":"jo","name":"Jordan (‫الأردن‬‎)","code":"+962"},
            {"key":"ki","name":"Kiribati","code":"+686"},
            {"key":"ie","name":"Ireland","code":"+353"},
            {"key":"kw","name":"Kuwait (‫الكويت‬‎)","code":"+965"},
            {"key":"kz","name":"Kazakhstan (Казахстан)","code":"+7"},
            {"key":"gh","name":"Ghana (Gaana)","code":"+233"},
            {"key":"la","name":"Laos (ລາວ)","code":"+856"},
            {"key":"lv","name":"Latvia (Latvija)","code":"+371"},
            {"key":"kg","name":"Kyrgyzstan (Кыргызстан)","code":"+996"},
            {"key":"lb","name":"Lebanon (‫لبنان‬‎)","code":"+961"},
            {"key":"lr","name":"Liberia","code":"+231"},
            {"key":"ly","name":"Libya (‫ليبيا‬‎)","code":"+218"},
            {"key":"li","name":"Liechtenstein","code":"+423"},
            {"key":"lu","name":"Luxembourg","code":"+352"},
            {"key":"mk","name":"Macedonia (FYROM) (Македонија)","code":"+389"},
            {"key":"mo","name":"Macau (澳門)","code":"+853"},
            {"key":"mg","name":"Madagascar (Madagasikara)","code":"+261"},
            {"key":"mw","name":"Malawi","code":"+265"},
            {"key":"ls","name":"Lesotho","code":"+266"},
            {"key":"my","name":"Malaysia","code":"+60"},
            {"key":"mv","name":"Maldives","code":"+960"},
            {"key":"je","name":"Jersey","code":"+44"},
            {"key":"ml","name":"Mali","code":"+223"},
            {"key":"mh","name":"Marshall Islands","code":"+692"},
            {"key":"ke","name":"Kenya","code":"+254"},
            {"key":"mr","name":"Mauritania (‫موريتانيا‬‎)","code":"+222"},
            {"key":"mq","name":"Martinique","code":"+596"},
            {"key":"yt","name":"Mayotte","code":"+262"},
            {"key":"md","name":"Moldova (Republica Moldova)","code":"+373"},
            {"key":"fm","name":"Micronesia","code":"+691"},
            {"key":"mc","name":"Monaco","code":"+377"},
            {"key":"mn","name":"Mongolia (Монгол)","code":"+976"},
            {"key":"me","name":"Montenegro (Crna Gora)","code":"+382"},
            {"key":"ms","name":"Montserrat","code":"+1664"},
            {"key":"ma","name":"Morocco (‫المغرب‬‎)","code":"+212"},
            {"key":"mt","name":"Malta","code":"+356"},
            {"key":"mz","name":"Mozambique (Moçambique)","code":"+258"},
            {"key":"mm","name":"Myanmar (Burma) (မြန်မာ)","code":"+95"},
            {"key":"nr","name":"Nauru","code":"+674"},
            {"key":"nc","name":"New Caledonia (Nouvelle-Calédonie)","code":"+687"},
            {"key":"nl","name":"Netherlands (Nederland)","code":"+31"},
            {"key":"np","name":"Nepal (नेपाल)","code":"+977"},
            {"key":"nz","name":"New Zealand","code":"+64"},
            {"key":"ng","name":"Nigeria","code":"+234"},
            {"key":"nu","name":"Niue","code":"+683"},
            {"key":"ni","name":"Nicaragua","code":"+505"},
            {"key":"lt","name":"Lithuania (Lietuva)","code":"+370"},
            {"key":"nf","name":"Norfolk Island","code":"+672"},
            {"key":"mu","name":"Mauritius (Moris)","code":"+230"},
            {"key":"mp","name":"Northern Mariana Islands","code":"+1670"},
            {"key":"kp","name":"North Korea (조선 민주주의 인민 공화국)","code":"+850"},
            {"key":"om","name":"Oman (‫عُمان‬‎)","code":"+968"},
            {"key":"ne","name":"Niger (Nijar)","code":"+227"},
            {"key":"pw","name":"Palau","code":"+680"},
            {"key":"pa","name":"Panama (Panamá)","code":"+507"},
            {"key":"ps","name":"Palestine (‫فلسطين‬‎)","code":"+970"},
            {"key":"pe","name":"Peru (Perú)","code":"+51"},
            {"key":"py","name":"Paraguay","code":"+595"},
            {"key":"ph","name":"Philippines","code":"+63"},
            {"key":"pg","name":"Papua New Guinea","code":"+675"},
            {"key":"pt","name":"Portugal","code":"+351"},
            {"key":"pl","name":"Poland (Polska)","code":"+48"},
            {"key":"pr","name":"Puerto Rico","code":"+1"},
            {"key":"qa","name":"Qatar (‫قطر‬‎)","code":"+974"},
            {"key":"no","name":"Norway (Norge)","code":"+47"},
            {"key":"ru","name":"Russia (Россия)","code":"+7"},
            {"key":"rw","name":"Rwanda","code":"+250"},
            {"key":"pk","name":"Pakistan (‫پاکستان‬‎)","code":"+92"},
            {"key":"bl","name":"Saint Barthélemy (Saint-Barthélemy)","code":"+590"},
            {"key":"re","name":"Réunion (La Réunion)","code":"+262"},
            {"key":"ro","name":"Romania (România)","code":"+40"},
            {"key":"mf","name":"Saint Martin (Saint-Martin (partie française))","code":"+590"},
            {"key":"sh","name":"Saint Helena","code":"+290"},
            {"key":"lc","name":"Saint Lucia","code":"+1758"},
            {"key":"pm","name":"Saint Pierre and Miquelon","code":"+508"},
            {"key":"ws","name":"Samoa","code":"+685", "icon": "&#x1F1FC&#x1F1F8"},
            {"key":"sm","name":"San Marino","code":"+378", "icon": "&#x1F1F8&#x1F1F2"},
            {"key":"rs","name":"Serbia (Србија)","code":"+381", "icon": "&#x1F1F7&#x1F1F8"},
            {"key":"sn","name":"Senegal (Sénégal)","code":"+221", "icon": "&#x1F1F8&#x1F1F3"},
            {"key":"vc","name":"Saint Vincent and the Grenadines","code":"+1784", "icon": ""},
            {"key":"sc","name":"Seychelles","code":"+248", "icon": "&#x1F1F8&#x1F1E8"},
            {"key":"kn","name":"Saint Kitts and Nevis","code":"+1869", "icon": "&#x1F1F0&#x1F1F3"},
            {"key":"sa","name":"Saudi Arabia (‫المملكة العربية السعودية‬‎)","code":"+966", "icon": "&#x1F1F8&#x1F1E6"},
            {"key":"sx","name":"Sint Maarten","code":"+1721", "icon": ""},
            {"key":"sg","name":"Singapore","code":"+65", "icon": "&#x1F1F8&#x1F1EC"},
            {"key":"sk","name":"Slovakia (Slovensko)","code":"+421", "icon": "&#x1F1F8&#x1F1F0"},
            {"key":"na","name":"Namibia (Namibië)","code":"+264", "icon": "&#x1F1F3&#x1F1E6"},
            {"key":"so","name":"Somalia (Soomaaliya)","code":"+252", "icon": "&#x1F1F8&#x1F1F4"},
            {"key":"si","name":"Slovenia (Slovenija)","code":"+386", "icon": "&#x1F1F8&#x1F1EE"},
            {"key":"kr","name":"South Korea (대한민국)","code":"+82", "icon": "&#x1F1F0&#x1F1F7"},
            {"key":"za","name":"South Africa","code":"+27", "icon": "&#x1F1FF&#x1F1E6"},
            {"key":"st","name":"São Tomé and Príncipe","code":"+239", "icon": "&#x1F1F8&#x1F1F9"},
            {"key":"sl","name":"Sierra Leone","code":"+232", "icon": "&#x1F1F8&#x1F1F1"},
            {"key":"lk","name":"Sri Lanka (ශ්‍රී ලංකාව)","code":"+94", "icon": "&#x1F1F1&#x1F1F0"},
            {"key":"sd","name":"Sudan (‫السودان‬‎)","code":"+249", "icon": "&#x1F1F8&#x1F1E9"},
            {"key":"ss","name":"South Sudan (‫جنوب السودان‬‎)","code":"+211", "icon": "&#x1F1F8&#x1F1F8"},
            {"key":"se","name":"Sweden (Sverige)","code":"+46", "icon": "&#x1F1F8&#x1F1EA"},
            {"key":"sj","name":"Svalbard and Jan Mayen","code":"+47", "icon": "&#x1F1F3&#x1F1F4"},
            {"key":"sz","name":"Swaziland Eswatini","code":"+268", "icon": "&#x1F1F8&#x1F1FF"},
            {"key":"ch","name":"Switzerland (Schweiz)","code":"+41", "icon": "&#x1F1E8&#x1F1ED"},
            {"key":"tw","name":"Taiwan (台灣)","code":"+886", "icon": "&#x1F1F9&#x1F1FC"},
            {"key":"sy","name":"Syria (‫سوريا‬‎)","code":"+963", "icon": "&#x1F1F8&#x1F1FE"},
            {"key":"tz","name":"Tanzania","code":"+255", "icon": "&#x1F1F9&#x1F1FF"},
            {"key":"th","name":"Thailand (ไทย)","code":"+66", "icon": "&#x1F1F9&#x1F1ED"},
            {"key":"tj","name":"Tajikistan","code":"+992", "icon": "&#x1F1F9&#x1F1EF"},
            {"key":"es","name":"Spain (España)","code":"+34", "icon": "&#x1F1EA&#x1F1F8"},
            {"key":"tg","name":"Togo","code":"+228", "icon": "&#x1F1F9&#x1F1EC"},
            {"key":"tt","name":"Trinidad and Tobago","code":"+1868", "icon": "&#x1F1F9&#x1F1F9"},
            {"key":"tk","name":"Tokelau","code":"+690", "icon": "&#x1F1F9&#x1F1F0"},
            {"key":"to","name":"Tonga","code":"+676", "icon": "&#x1F1F9&#x1F1F4"},
            {"key":"tl","name":"Timor-Leste","code":"+670", "icon": "&#x1F1F9&#x1F1F1"},
            {"key":"tr","name":"Turkey (Türkiye)","code":"+90", "icon": "&#x1F1F9&#x1F1F7"},
            {"key":"tv","name":"Tuvalu","code":"+688", "icon": "&#x1F1F9&#x1F1FB"},
            {"key":"sb","name":"Solomon Islands","code":"+677", "icon": "&#x1F1F8&#x1F1E7"},
            {"key":"tn","name":"Tunisia (‫تونس‬‎)","code":"+216", "icon": "&#x1F1F9&#x1F1F3"},
            {"key":"tm","name":"Turkmenistan","code":"+993", "icon": "&#x1F1F9&#x1F1F2"},
            {"key":"sr","name":"Suriname","code":"+597", "icon": "&#x1F1F8&#x1F1F7"},
            {"key":"ua","name":"Ukraine (Україна)","code":"+380", "icon": "&#x1F1FA&#x1F1E6"},
            {"key":"ae","name":"United Arab Emirates (‫الإمارات العربية المتحدة‬‎)","code":"+971", "icon": "&#x1F1E6&#x1F1EA"},
            {"key":"vi","name":"U.S. Virgin Islands","code":"+1340", "icon": "&#x1F1FB&#x1F1EE"},
            {"key":"uy","name":"Uruguay","code":"+598", "icon": "&#x1F1FA&#x1F1FE"},
            {"key":"uz","name":"Uzbekistan (O\'zbekiston)","code":"+998", "icon": "&#x1F1FA&#x1F1FF"},
            {"key":"ug","name":"Uganda","code":"+256", "icon": "&#x1F1FA&#x1F1EC"},
            {"key":"va","name":"Vatican City (Città del Vaticano)","code":"+39", "icon": "&#x1F1FB&#x1F1E6"},
            {"key":"vu","name":"Vanuatu","code":"+678", "icon": "&#x1F1FB&#x1F1FA"},
            {"key":"vn","name":"Vietnam (Việt Nam)","code":"+84", "icon": "&#x1F1FB&#x1F1F3"},
            {"key":"ve","name":"Venezuela","code":"+58", "icon": "&#x1F1FB&#x1F1EA"},
            {"key":"tc","name":"Turks and Caicos Islands","code":"+1649", "icon": "&#x1F1F9&#x1F1E8"},
            {"key":"wf","name":"Wallis and Futuna","code":"+681", "icon": "&#x1F1FC&#x1F1EB"}, 
            {"key":"ye","name":"Yemen (‫اليمن‬‎)","code":"+967", "icon": "&#x1F1FE&#x1F1EA"},
            {"key":"eh","name":"Western Sahara (‫الصحراء الغربية‬‎)","code":"+212", "icon": "&#x1F1EA&#x1F1ED"},
            {"key":"zm","name":"Zambia","code":"+260" , "icon": "&#x1F1FF&#x1F1F2"},
            {"key":"zw","name":"Zimbabwe","code":"+263", "icon": "&#x1F1FF&#x1F1FC"},
          ];
    }

}

export default CountryCodes;